### ISSUE TITLE
Invalid Signatures

### ISSUE THREAD

**Issue by tom-wray** [advplyr/audiobookshelf-ppa#2]
I get the following error when trying to install on Linux.

`GPG error: https://advplyr.github.io/audiobookshelf-ppa ./ InRelease: The following signatures were invalid: F0BFFF44BC7DE9D288CF75C912269E7DCE24DB03`

**Comment by advplyr** [comment]
What is the command you are entering that is producing that error?

**Comment by Andi-bz** [comment]
Same here.
`root@audiobookshelf:/# curl -s --compressed "https://advplyr.github.io/audiobookshelf-ppa/KEY.gpg" | sudo apt-key add - && sudo curl -s --compressed -o /etc/apt/sources.list.d/audiobookshelf.list "https://advplyr.github.io/audiobookshelf-ppa/audiobookshelf.list" && sudo apt update && sudo apt install audiobookshelf
OK
Get:1 https://advplyr.github.io/audiobookshelf-ppa ./ InRelease [2068 B]
Err:1 https://advplyr.github.io/audiobookshelf-ppa ./ InRelease
  The following signatures were invalid: F0BFFF44BC7DE9D288CF75C912269E7DCE24DB03
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
W: GPG error: https://advplyr.github.io/audiobookshelf-ppa ./ InRelease: The following signatures were invalid: F0BFFF44BC7DE9D288CF75C912269E7DCE24DB03
E: The repository 'https://advplyr.github.io/audiobookshelf-ppa ./ InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@audiobookshelf:/#`

**Comment by advplyr** [comment]
I'm not sure what the problem is since I can't reproduce it. Someone else with this issue was also unable to install the debian package manually. Are you able to install the debian package?

**Comment by Quietus** [comment]
I think I've found the issue https://askubuntu.com/questions/1240263/how-to-handle-invalid-signature-in-apt-get

Your key is using digest algo 2

**Comment by advplyr** [comment]
Ah yeah you're probably right. v2 is coming soon with major updates so I'll try to get this updated for the release of v2.

**Comment by leprasmurf** [comment]
Manually installing the package continues to work.  I don't remember where I found it, but someone recommended adding `[trusted=yes]` to the repo line, which lets me use the PPA, but it'd be nice to have a valid GPG key.

**Comment by TgSeed** [comment]
[v2.0.22](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.22) is here and yet this issue too.
@advplyr Fix it please, Thanks.

**Comment by cloud-affair** [comment]
the [trusted=yes] is not a great idea. It just skips the gpg validation, making the certificate generation pointless. If everyone using ABS is doing that - this is not secure.

Follow up question: why don't you mirror these packages on Ubuntu's Launchpad and instruct users to add the ppa that way instead of skipping over the cert in the first place? it would be much simpler and would actually make use of the secure signatures. Not to mention, Ubuntu apt is has said they plan on eliminating the ability for any repos to be linked unless they're secured and all files signed. So if this isn't addressed soon, no one will be able to use a repo and we will all have to periodically come back to install new releases.

**Comment by advplyr** [comment]
I thought I had resolved this already but then I checked the key again and it was still SHA1

This should be resolved now in [v2.2.5](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.5) but let me know if you still have issues.

You will need to get the new key to get the latest version.

If this works and you can remove `[trusted=yes]` please follow up.

**Comment by cloud-affair** [comment]
That worked perfectly thanks!

For anyone coming to this issue later, I removed the Trusted line in the .sources file (the format which is replacing .list files), downloaded the new key, and ran apt upgrade and it worked just fine. 

For advplyr: since apt is changing from lists to sources, and apt-key is being deprecated, here are the cmds to update the Audiobookshelf.org Installer page:

curl -fsSL https://advplyr.github.io/audiobookshelf-ppa/KEY.gpg | gpg --dearmor | sudo tee /etc/apt/keyrings/audiobookshelf.gpg > /dev/null

cat <<EOF | sudo tee /etc/apt/sources.list.d/audiobookshelf.sources
Types: deb
URIs: https://advplyr.github.io/audiobookshelf-ppa/
Suites: ./
Components: 
Signed-By: /etc/apt/keyrings/audiobookshelf.gpg
EOF

Notes: 
As for where to store the key, I just want to keep the apt certs in /etc/apt/ but there is some argument that static files should be written to /usr/shared/. Feel free to change it, but this location makes sense to me. 

Then after users have downloaded the cert the next command will form the proper .sources file in /etc/apt/sources.list.d. The command requires CTRL+enter between lines, then a full enter after the second EOF to write the file. Alternatively, creating an /etc/apt/sources.list.d/audiobookshelf.sources file with vi or nano would be fine too, then just copy between Types line and EOF  and save.
